version: '3'
services:
  qdrant:
    image: qdrant/qdrant:v1.7.1
    container_name: ragika_qdrant
    ports:
      - '6333:6333'
    volumes:
      - qdrant_data:/qdrant/storage
  embeddings:
    image: ghcr.io/huggingface/text-embedding-inference:latest
    container_name: ragika_embeddings
    ports:
      - '8080:80'
    environment:
      - MODEL_ID=BAAI/bge-m3
      - NUM_SHARDS=1
  reranker:
    image: ghcr.io/huggingface/text-embedding-inference:latest
    container_name: ragika_reranker
    ports:
      - '8081:80'
    environment:
      - MODEL_ID=BAAI/bge-reranker-v2-m3
      - TASK=rerank
      - MAX_INPUT_TOKEN_LENGTH=8192
volumes:
  qdrant_data: