export interface DocumentChunk {
  /** Unique identifier for this chunk */
  id: string;
  /** Identifier of the original document this chunk belongs to */
  documentId: string;
  /** High level category assigned to this document */
  category: string;
  /** The raw text of this chunk */
  text: string;
  /** Optional embedding vector for this chunk */
  embedding?: number[];
}

export interface DocumentRecord {
  /** Unique identifier for the document */
  id: string;
  /** Category assigned to this document */
  category: string;
  /** Original file name or description */
  title: string;
  /** Date the document was ingested */
  createdAt: string;
}

export interface ChatQueryRequest {
  /** The user's natural language query */
  query: string;
  /** Optionally restrict retrieval to a specific category */
  category?: string;
}

export interface Citation {
  /** Document ID being cited */
  documentId: string;
  /** Chunk ID within the document */
  chunkId: string;
}

export interface ChatQueryResponse {
  /** Final answer generated by the LLM */
  answer: string;
  /** List of citations supporting the answer */
  citations: Citation[];
}

export interface IngestTextRequest {
  /** Text to be ingested and indexed */
  text: string;
  /** Category assigned to this text */
  category: string;
  /** Optional title for the document */
  title?: string;
}

export interface IngestTextResponse {
  /** ID of the created document */
  documentId: string;
  /** Number of chunks created */
  chunks: number;
}